#spring:
#
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/yogee2
#    username: jackqth
#    password: jackqth13
#    driver-class-name: com.mysql.jdbc.Driver
#
#server:
#
#  port: 8088
#  tomcat:
#    uri-encoding: UTF-8
#
#debug: true
#

